### ISSUE TITLE
GitLab service fails to start on Ubuntu 14.04

### ISSUE THREAD

**Issue by rbugajewski** [atomic-penguin/cookbook-gitlab#77]
After the cookbook installs GitLab and all related packages, it fails to start via the provided init.d script on Ubuntu 14.04. The issue is that `bundle` isn’t in the `PATH`. The solution is to either extend the `PATH` variable in the init script (`PATH="$PATH:/srv/git/bin"`) or to create a symbolic link inside a `PATH` folder to the bundle command:

```
link "/usr/local/bin/bundle" do
  to "/srv/git/bin/bundle"
end
```

**Comment by jeremyolliver** [comment]
I'm also testing on Ubuntu 14.04 and appears to all be working fine now. `/srv/git/bin/` should be part of the path via `/srv/git/.profile` since the git user's home is `/srv/git` - this appears to have been corrected in issue #66. I'm going to go ahead and close this issue, if this is still failing for you on the master branch of this cookbook, please re-open
